name: prueba_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy: ^6.0.2
  cupertino_icons: ^1.0.8
  flutter_blue_plus: 1.34.5
  audioplayers: ^5.2.1
  http: ^1.0.0
  shared_preferences: ^2.5.3
  logging: ^1.2.0
  provider: ^6.1.5
  permission_handler: ^11.3.0
  license_checker: ^1.6.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/